project:
  type: website
  
execute:
  freeze: auto

website:
  title: "Steve Martin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: software.qmd
        text: Software
      - href: publications.qmd
        text: Research and publications
    right:
      - href: https://github.com/marberts
        text: "{{< fa brands github >}}"
      - href: https://marberts.r-universe.dev
        text: "{{< fa rocket >}}"
      - href: https://orcid.org/0000-0003-2544-9480
        text: "{{< fa brands orcid >}}"
      - href: https://scholar.google.ca/citations?user=CEJjbeoAAAAJ&hl=en
        text: "{{< fa brands google-scholar >}}"
      - href: mailto:marberts@protonmail.com
        text: "{{< fa envelope >}}"
  favicon: img/favicon-32x32.png
  site-url: https://marberts.github.io

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
