---
title: "About me"
---

## Interests

- Price statistics and index numbers.

- R programming and data science.

- Industrial organization.

- Environmental economics.

## Education

### Degrees

- PhD Economics, University of Ottawa, 2013-2017.

- B.SocSc Economics, University of Ottawa, 2009-2012.

### Other education

- European Summer School in Environmental Economics, Venice International University, 2015.

- Visiting Scholar, University of Michigan, 2015.

## Work experience

- Principal researcher, Statistics Canada, 2024--present

- Data scientist, Government of Canada, 2022--2024.

- Economist, Statistics Canada, 2017--2022.

- Part-time professor of economics, University of Ottawa, 2016--2018.

## Awards and Prizes

- Outstanding Contribution Award, Statistics Canada, 2020.

- Youth Leadership Award, Statistics Canada, 2018.

- Pierre Laberge prize for outstanding doctoral thesis, University of Ottawa, 2018.

- Joseph-Armande Bombardier Canadian Graduate Scholarship, SSHRC, 2015.
