---
title: "Research and Publications"
---

## Software papers

- Martin, S. (2024). [piar: Price Index Aggregation in R](https://doi.org/10.21105/joss.06781). *Journal of Open Source Software*, 9(101): 6781.

- Kirby-McGregor, M. and Martin, S. (2019). [An R package for calculating repeat-sale price indices](https://www.revistadestatistica.ro/2019/09/an-r-package-for-calculating-repeat-sale-price-indices/). *Romanian Statistical Review*, 3/2019: 17-33.

## Statistics Canada publications

- Martin, S. (2021). [A note on general decompositions for price indexes](https://publications.gc.ca/pub?id=9.900889&sl=0). *Prices Analytical Series*. Statistics Canada Catalogue 62F0014M.

- Martin, S. (2020). [Gearing up to stay open: Trends in businesses' needs for personal protective equipment since July](https://publications.gc.ca/pub?id=9.892309&sl=0). *Statcan COVID-19: Data Insights for a Better Canada*. Statistics Canada Catalogue 45-28-0001.

- Martin, S. (2020). [Gearing up to restart: Businesses' need for personal protective equipment](https://publications.gc.ca/pub?id=9.890470&sl=0). *Statcan COVID-19: Data Insights for a Better Canada*. Statistics Canada Catalogue 45-28-0001.

- Martin, S. and Rouleau, B. (2020). [An exploration of work, learning, and work-integrated learning in Canada using the Longitudinal and International Study of Adults](https://publications.gc.ca/pub?id=9.883817&sl=0). *LISA Research Paper Series*. Statistics Canada Catalogue 89-648-X. 

- Martin, S. (2019). [Methodology of the Residential Property Price Index (RPPI)](https://publications.gc.ca/pub?id=9.878018&sl=0). *Prices Analytical Series*. Statistics Canada Catalogue 62F0014M.

- Martin, S. (2018). [The association between job flexibility and job satisfaction](https://publications.gc.ca/pub?id=9.865732&sl=0). *Insights on Canadian Society*. Statistics Canada Catalogue 75-006-X.

- Martin, S. (2018). [In sickness and in health: The association between health and household income](https://publications.gc.ca/pub?id=9.857907&sl=0). *LISA Research Paper Series*. Statistics Canada Catalogue 89-648-X.

## Academic publications

- Heyes, A., Kapur, S., Kennedy, P., Martin, S., and Maxwell, J. (2020). [But What Does it Mean? Competition between Products Carrying Alternative Green Labels when Consumers are Active Acquirers of Information](https://doi.org/10.1086/706548). *Journal of the Association of Environmental and Resource Economists*, 7(2): 243-277.

- Martin, S. (2019). [Moral management in competitive markets](https://doi.org/10.1111/jems.12283). *Journal of Economics and Management Strategy*, 28(3): 541–560.

- Heyes, A. and Martin, S. (2018). [Inefficient social labels: Strategic proliferation and fragmentation in the market for certification](https://doi.org/10.1111/jems.12236). *Journal of Economics and Management Strategy*, 27(2): 206–220.

- Heyes, A., Lyon, T. P., and Martin, S. (2018). [Salience games: Private politics when public attention is limited](https://doi.org/10.1016/j.jeem.2018.02.003). *Journal of Environmental Economics and Management*, 88: 396–410.

- Martin, S. and Rivers, N. (2018). [Information provision, market incentives, and household electricity consumption: Evidence from a large-scale field deployment](https://doi.org/10.1086/694036). *Journal of the Association of Environmental and Resource Economists*, 5(1): 207–231.

- Heyes, A. and Martin, S. (2017). [Social labeling by competing NGOs: A model with multiple issues and entry](https://doi.org/10.1287/mnsc.2015.2419). *Management Science*, 63(6): 1800–1813.

- Heyes, A. and Martin, S. (2016). [Fuzzy products](https://doi.org/10.1016/j.ijindorg.2015.12.003). *International Journal of Industrial Organization*, 45: 1–9.

- Heyes, A. and Martin, S. (2015). [NGO mission design](https://doi.org/10.1016/j.jebo.2015.08.007). *Journal of Economic Behavior & Organization*, 119: 197–210.

## Conference papers

- Brown, C. and Martin, S. (2025). [Interim Report: Survey of CPI Production Systems](https://un-task-team-for-scanner-data.github.io/production-systems-survey/report-site/). *UNECE Meeting of the Group of Experts on Consumer Price Indices*.

- Burnett-Isaacs, K. and Martin, S. (2019). [Unifying Approach to Statistics Canada´s Residential Property Price Index](https://stats.unece.org/ottawagroup/download/f561.pdf). *UNECE Ottawa Group on Price Indices*.

- Burnett-Isaacs, K. and Martin, S. (2019). [Constructing a Resale Residential Property Price Index for Vancouver using Repeat Sales](https://stats.unece.org/ottawagroup/download/f584.pdf). *UNECE Ottawa Group on Price Indices*.

## Conference presentations

- Statistics Canada's Price Measurement Advisory Committee (Ottawa, 2019 and 2025).

- 52nd Annual Conference of the Canadian Economics Association (Montreal, 2018).

- Annual meeting of the Canadian Public Economics Group (Montreal, 2016).

- 50th Annual Conference of the Canadian Economics Association (Ottawa, 2016).

- 4th Canadian Early Career Workshop in Environmental Economics (Ottawa, 2016).

- 14th Annual International Industrial Organization Conference (Philadelphia, 2016).

- EAERE-FEEM-VIU European Summer School (Venice, 2015).

- 5th World Congress of Environmental and Resource Economists (Istanbul, 2014).

- 12th Annual International Industrial Organization Conference (Chicago, 2014).

## Refereed for

- Canadian Journal of Economics.
- Environmental and Resource Economics.
- Journal of the Association of Environmental and Resource Economists.
- Journal of Economics and Management Strategy.
- Journal of Environmental Economics and Management.
- Journal of Open Source Software.

